hostname: "localhost:3000"
oauth_client_id: "<google app id here>.apps.googleusercontent.com"
oauth_client_secret: "<google app secret here>"
jwt_secret: "<your secret here>"
jwt_ttl: "24h"
default_redirect_url: "http://example.com"
admin:
  - "admin@example.com"
  - "admin2@example.com"
