name: dockerhub

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v3

      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          build-contexts: |
            github=.
          build-args: |
            TAGVERSION=${{ github.ref_name }}
          tags: |
            shyym/shortlink:latest
            shyym/shortlink:${{ github.ref_name }}
          load: ${{ vars.DOCKERHUB_LOAD }}
          push: ${{ vars.DOCKERHUB_PUSH }}